
# apiVersion: v1
# kind: Pod
# metadata:
#   name: multi-container
#   # namespace: roboshop
# spec:
#   containers:
#   - name: nginx
#     image: nginx

#   - name: sidecar
#     image: almalinux:8
#     command: sleep 20s

apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-data
          mountPath: /usr/share/nginx/html  # nginx serve karega isi folder se

    - name: content-writer
      image: busybox
      command: ['sh', '-c', 'echo "Hello Nginx" > /usr/share/nginx/html/index.html && sleep 3600']
      volumeMounts:
        - name: html-data
          mountPath: /usr/share/nginx/html  # same volume mount — shared folder

  volumes:
    - name: html-data
      emptyDir: {}   # temporary shared storage between containers


   

