
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: dev
    app: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http-web-srv
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    environment: dev
    app: frontend
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 30007 # Node Port (30000-32767)