apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: dev
    app: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http-web-srv

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    environment: dev
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: http-web-srv